### ISSUE TITLE
Receiving a message "Invalid body: Version mismatch." when using /token/generate endpoint while encrypting with the provided scripts

### ISSUE THREAD

**Issue by theandypeterson** [IABTechLab/uid2docs#126]
When testing out the `/token/generate` endpoint, I'm receiving the following message: 

`{"message":"Invalid body: Version mismatch.","status":"client_error"}`

I'm following the steps from the `/token/generate` [documentation](https://github.com/IABTechLab/uid2docs/blob/main/api/v2/endpoints/post-token-generate.md#token-generation-policy), using the Python scripts provide in the [Encyrption/Decryption docs](https://github.com/IABTechLab/uid2docs/blob/main/api/v2/getting-started/gs-encryption-decryption.md):
```
echo '{"email_hash": "tMmiiTI7IaAcPpQPFQ65uMVCWH8av9jw4cwf/F5HVRQ="}' \
  | encrypt_request.py {redacted} \
  | curl -X POST 'https://prod.uidapi.com/v2/token/generate' -H 'Authorization: Bearer YourToken{redacted}' -d @- \
  | decrypt_response.py {redacted}
```
 I am replacing the key and secret with my own credentials.

`encrypt_request.py` script: 
```
import base64
import os
import sys
import time
from datetime import datetime

from Crypto.Cipher import AES

secret = base64.b64decode(sys.argv[1])
payload = "".join(sys.stdin.readlines())

iv = os.urandom(12)
cipher = AES.new(secret, AES.MODE_GCM, nonce=iv)

millisec = int(time.time() * 1000)
nonce = os.urandom(8)

print(f'Request timestamp: {datetime.fromtimestamp(millisec/1000)}', file=sys.stderr)
print(f'Request nonce: {int.from_bytes(nonce, "big")}', file=sys.stderr)
print(file=sys.stderr)

body = bytearray(millisec.to_bytes(8, 'big'))
body += bytearray(nonce)
body += bytearray(bytes(payload, 'utf-8'))

ciphertext, tag = cipher.encrypt_and_digest(body)

envelope = bytearray(b'\x01')
envelope += bytearray(iv)
envelope += bytearray(ciphertext)
envelope += bytearray(tag)

print(base64.b64encode(bytes(envelope)).decode() + "\n")
```

I tried updating the `encrypt_python` script to have a different value for the version byte in the request envelope, but no change in behavior occurred. Additionally, removing that byte from the request envelope returned a different error: "Invalid Body Length", confirming that the endpoint was indeed receiving the updated envelope as I made changes.

I'm running Python v3.11.2.

**Comment by jcerone** [comment]
@atarassov-ttd I'm now picking up this work from @theandypeterson. Do you think this issue is related to https://github.com/IABTechLab/uid2docs/issues/55? Is there any chance we are simply hitting the wrong subdomain here? Or would you say that expired credentials are the more likely culprit?

**Comment by scong-ttd** [comment]
Hi @jcerone let me try to reproduce the issue. The python snippet in documentation is tested in python 3.8

**Comment by scong-ttd** [comment]
I cannot reproduce the issue with python v3.11.2 on debian bullseye. The version byte mismatch means your first byte in the envelop is not \x01. Can you give more info on what OS and shell you are using to run the command?

**Comment by jcerone** [comment]
Hi @scong-ttd I'm running the following: 

```
macOS Ventura v13.3
zsh shell
Python 3.11.2
```

Here's the output I'm seeing given an arbitrary AES secret I generated as an example: 

```
echo '{"email_hash": "tMmiiTI7IaAcPpQPFQ65uMVCWH8av9jw4cwf/F5HVRQ="}' \
  | python3 encrypt_request.py 3c7d1d1a8e9a54f9f3a3b3c1b8ab849c
Request timestamp: 2023-04-05 10:11:42.056000
Request nonce: 883117248792742734

bytearray(b'\x01\x94\xbc\xc2\x03\xbb^\xb8\x98\x8c\xe5\x84P|q\x1c\xb2xl\xab\xee\xf3\x96&\x01\\\xdd\xdd5\x84\xe4\xa2U\xf5\x00\xa2\x97\x1d\xa5\x1d\x8a6\x9c\x99\x17g`iO4\x91\x01+\x00\xceS\x8f\xcd\x1aI\xe9\xb3\xc6\x97\xebK\xcar?\xa3\x0bN\xf6\xb9u\x11\x92[\x0byna\x85\xc4X\x82\xb5\xf75)\x16\x03-\x8eBo$\x90\xfb<o\xbf\x13V\x9b\x92\xe8%')
AZS8wgO7XriYjOWEUHxxHLJ4bKvu85YmAVzd3TWE5KJV9QCilx2lHYo2nJkXZ2BpTzSRASsAzlOPzRpJ6bPGl+tLynI/owtO9rl1EZJbC3luYYXEWIK19zUpFgMtjkJvJJD7PG+/E1abkugl
```

From the above, it appears the first byte is indeed `\x01`.

**Comment by jcerone** [comment]
Hi @scong-ttd that's just a 32 letter code ChatGPT generated for me 😜. For clarity, I used the secret we were given as-is in my actual request. I just cleared that up by just showing it as redacted. 

In the following code, I used the credentials provided to us by Trade Desk and received the invalid body error. Should I request new keys in this case, since the one's I've been given appear to be invalid? 

```
echo '{"email": "test@example.com"}' \
  | python3 encrypt_request.py {redacted} \
  | curl -X POST 'https://prod.uidapi.com/v2/token/generate' -H 'Authorization: Bearer {redacted}' -d @- \
  | python3 decrypt_response.py {redacted}

-----------------------------------------------------------------------------------

Request timestamp: 2023-04-05 10:14:38.034000
Request nonce: {redacted}

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   400  100    77  100   323     99    417 --:--:-- --:--:-- --:--:--   518

Error response:
{
    "message": "Invalid body: Check encryption key (ClientSecret)",
    "status": "client_error"
}
```

**Comment by jon8787** [comment]
Hi @jcerone, we've sent the keys to Gareth. The one that should be used in this case has a name ending in "-Generator"
The error you're receiving indicates the API key is correct (Authorization: Bearer {redacted}), but the secret key or the encryption code is incorrect.

**Comment by jcerone** [comment]
Hi @jon8787 I'm not sure I'm familiar with Gareth, but it's good to know that one half of our setup is correct and that the problem is with our secret key rather than our implementation. I requested updated credentials from TTD yesterday and will let you know how they work!
