### ISSUE TITLE
First party cookie or web storage?

### ISSUE THREAD

**Issue by marco-ita** [IABTechLab/uid2docs#14]
Hi there, 
I work in the ad tech industry as a consultant and I am informing myself on the details of UID 2.0 in order to provide consultancy to clients. 
I read here that Publishers store the UID 2.0 token client side through first party cookies. 
But here https://adtechexplained.com/unified-id-2-0-explained/ I read that it does that through web storage. 
Could you explain which one is true?
Thanks, 
Marco.

**Comment by adtechexplained** [comment]
I made this assumption based on the "disconnect" mechanism:

"Remove UID2 tokens from the user's local storage thwne they log out." (typo from doc)

Can you please clarify if the client-side identity SDK uses local storage, 1P cookies or both?

**Comment by lionell-pack-ttd** [comment]
How the tokens are stored is an implementation detail which may change over time, and depending on the publisher and configuration of the user's browser.

The official UID2 JavaScript SDK only uses 1st-party cookies at this stage, but that may change. I am aware of some implementations which may store the cookie in local storage instead.

As this is an old conversation, I'll close it, but feel free to continue the conversation if this doesn't answer your question.
