### ISSUE TITLE
Precisely describe how UID2 tokens are encrypted

### ISSUE THREAD

**Issue by ekr** [IABTechLab/uid2docs#21]
The explainer says:

>  A cryptographic nonce is generated and appended to the UID2, which is then encrypted to create the UID2 Tokens.
>    *  A nonce is an arbitrary number that may only be used once.
>    *  AES/CBC/PKCS5P with 256-bit keys are used for encryption and rotate on a daily basis.

This is not sufficiently precise to implement (or analyze). The best I can come up with is that this is:

```
AES-256(K, UID || Nonce || PKCS-5 padding)
```

Is this correct? What is the IV and how is it generated? How is message integrity provided for or is it not?

**Comment by atarassov-ttd** [comment]
Apologies for a late response. We are planning to add more detailed explanation of how token encryption works in the future. In the meantime, could you please help us understand what you are trying to achieve?

**Comment by ekr** [comment]
I'm trying to get to the point where I understand the security properties of the system.

**Comment by atarassov-ttd** [comment]
Until we have the documentation ready (no ETA yet), it is best if you could [contact us](https://github.com/IABTechLab/uid2docs/tree/main/api#contact-info) directly.

**Comment by atarassov-ttd** [comment]
Closing for now: adding the requested documentation is on the roadmap for the team, however we do not have an immediate ETA.
