### ISSUE TITLE
Need PDF for all the uid 2.0 docs

### ISSUE THREAD

**Issue by raychaudhuri-amitava** [IABTechLab/uid2docs#214]
Is there any way to convert the entire site into a PDF.

**Comment by genwhittTTD** [comment]
Thank you for your comment. I'm looking into it and will be in touch.

**Comment by genwhittTTD** [comment]
Hello. I heard back on this. Sorry, but, we have no plan currently to create a PDF for the UID2 docs. It's possible that there's a way to do it with an external tool but I don't know of one.

**Comment by genwhittTTD** [comment]
Closing this issue.
