### ISSUE TITLE
[Client-Side Identity SDK 0.0.1a] Unable to store and retrieve values in cookie

### ISSUE THREAD

**Issue by miyaichi** [IABTechLab/uid2docs#30]
# Overview
Unable to store and retrieve values in cookie with [Client-Side Identity SDK 0.0.1a](https://integ.uidapi.com/static/js/uid2-sdk-0.0.1a.js).

# Steps to reproduce

In the following html, both Identity and AdvertisingToken are shown as undefined.

```html
<html>
<body>
<script src="https://integ.uidapi.com/static/js/uid2-sdk-0.0.1a.js" type="text/javascript"></script>

<script>
  var result =
    '{' +
    '  "body": {' +
    '    "advertising_token": "AdvertisingToken",' +
    '    "refresh_token": "RefreshToken"' +
    '  },' +
    '  "status": "success"' +
    '}';
  __uid2.init(result);

  var value = __uid2.getIdentity();
  document.write("Identity: " + JSON.stringify(value) + "<br/>");

  var value = __uid2.getAdvertisingToken();
  document.write("AdvertisingToken: " + JSON.stringify(value) + "<br/>");
</script>
</body>
</html>
```

```html
Identity: undefined
AdvertisingToken: undefined
```

# How to get in trouble if you don't fix it

The response from GET /token/generate could not be stored in the cookie and the value could not be retrieved.

# Cause

Response Format of UID2 API is not interpreted correctly. The Response Format is {"body": {}, "status": "<status>"}, but the code assumes that the "identity" element is present.

# Proposed fix

I propose to rewrite init, refreshIfNeeded, getAdvertisingToken of Class UID2 as follows.

```js script
this.init = (identity) => {
    if (identity) {
        this.setIdentity(identity);
    }
    else {
        this.refreshIfNeeded();
    }
};
this.refreshIfNeeded = () => {
    const identity = this.getRefreshToken();
    if (refresh_token) {
        const url = "https://prod.uidapi.com/token/refresh?refresh_token=" + encodeURIComponent(refresh_token);
        const req = new XMLHttpRequest();
        req.overrideMimeType("application/json");
        var cb = this.handleRefreshResponse;
        req.open("GET", url, false);
        req.onload = function () {
            cb(req.responseText);
        };
        req.send();
    }
};

this.getAdvertisingToken = () => {
    const identity = this.getIdentity();
    if (identity && "body" in identity) {
        return identity["body"]["advertising_token"];
    }
};
this.getRefreshToken = () => {
    const identity = this.getIdentity();
    if (identity && "body" in identity) {
        return identity["body"]["refresh_token"];
    }
};
```

**Comment by lionell-pack-ttd** [comment]
Sorry for the slow response to this.

The response from the token generate API is not intended to be passed directly to `init`. The `init` function takes a number of configuration options, which may (or may not) include the identity property. Version 0.0.1a didn't support any other configuration options, but using this pattern allowed us to avoid breaking changes as new options were supported.

Please refer to the [examples repository](https://github.com/IABTechLab/uid2-examples) for correct usage.
