### ISSUE TITLE
[Client-Side Identity SDK 1.0.0] get problem while using SDK with google GPT.

### ISSUE THREAD

**Issue by bys42** [IABTechLab/uid2docs#36]
Hello, I get some error message while using [SDK 1.0.0](https://prod.uidapi.com/static/js/uid2-sdk-1.0.0.js) with google GPT:
```
uid2-sdk-1.0.0.js:25 Uncaught TypeError: Cannot read properties of undefined (reading 'push') at uid2-sdk-1.0.0.js:25:40
```
## Steps to reproduce
in html, put uid2-sdk after gpt like below.
```
<html>
<head>
    <script src="https://securepubads.g.doubleclick.net/tag/js/gpt.js"></script>
    <script src="https://prod.uidapi.com/static/js/uid2-sdk-1.0.0.js"></script>
</head>
<body>
</body>
</html>
```
Not sure if it is ok to avoid the issue by loading UID2 SDK before GPT instead.

**Comment by lionell-pack-ttd** [comment]
Sorry for the delay responding to this. I've tried your reproduction and there is no error - it's possible this has already been fixed, probably at Google's end. I'll close this for now, but please re-open it if you're still encountering the problem and provide which browser version you're receiving the console error in.
