### ISSUE TITLE
Encrypt and Decrypt methods inside SDK

### ISSUE THREAD

**Issue by coderkot** [IABTechLab/uid2docs#46]
It would be great if you implement the method for encrypting the request body and the method for decrypting the response inside the SDK! It's will very simplify and speed up the integration of your SDK. Thanks!

**Comment by atarassov-ttd** [comment]
UID2 development team is working on this. So far the functionality has been implemented in the Java SDK: https://github.com/IABTechLab/uid2-client-java

Please let us know if this is what you are looking for.
